// flow-typed signature: 47ef3f21bf030dd9778030093058afc1
// flow-typed version: <<STUB>>/dom-parser_v^0.1.5/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom-parser/lib/Dom' {
  declare module.exports: any;
}

declare module 'dom-parser/lib/DomParser' {
  declare module.exports: any;
}

declare module 'dom-parser/lib/Node' {
  declare module.exports: any;
}

declare module 'dom-parser/test/getAttribute' {
  declare module.exports: any;
}

declare module 'dom-parser/test/getElementById' {
  declare module.exports: any;
}

declare module 'dom-parser/test/getElementsByClassName' {
  declare module.exports: any;
}

declare module 'dom-parser/test/getElementsByName' {
  declare module.exports: any;
}

declare module 'dom-parser/test/getElementsByTagName' {
  declare module.exports: any;
}

declare module 'dom-parser/test/invalidHTML' {
  declare module.exports: any;
}

declare module 'dom-parser/test/outerHTML' {
  declare module.exports: any;
}

declare module 'dom-parser/test/textContent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dom-parser/index' {
  declare module.exports: $Exports<'dom-parser'>;
}
declare module 'dom-parser/index.js' {
  declare module.exports: $Exports<'dom-parser'>;
}
declare module 'dom-parser/lib/Dom.js' {
  declare module.exports: $Exports<'dom-parser/lib/Dom'>;
}
declare module 'dom-parser/lib/DomParser.js' {
  declare module.exports: $Exports<'dom-parser/lib/DomParser'>;
}
declare module 'dom-parser/lib/Node.js' {
  declare module.exports: $Exports<'dom-parser/lib/Node'>;
}
declare module 'dom-parser/test/getAttribute.js' {
  declare module.exports: $Exports<'dom-parser/test/getAttribute'>;
}
declare module 'dom-parser/test/getElementById.js' {
  declare module.exports: $Exports<'dom-parser/test/getElementById'>;
}
declare module 'dom-parser/test/getElementsByClassName.js' {
  declare module.exports: $Exports<'dom-parser/test/getElementsByClassName'>;
}
declare module 'dom-parser/test/getElementsByName.js' {
  declare module.exports: $Exports<'dom-parser/test/getElementsByName'>;
}
declare module 'dom-parser/test/getElementsByTagName.js' {
  declare module.exports: $Exports<'dom-parser/test/getElementsByTagName'>;
}
declare module 'dom-parser/test/invalidHTML.js' {
  declare module.exports: $Exports<'dom-parser/test/invalidHTML'>;
}
declare module 'dom-parser/test/outerHTML.js' {
  declare module.exports: $Exports<'dom-parser/test/outerHTML'>;
}
declare module 'dom-parser/test/textContent.js' {
  declare module.exports: $Exports<'dom-parser/test/textContent'>;
}
