// flow-typed signature: 307596c0a030789b441107c59329a6bf
// flow-typed version: <<STUB>>/webtorrent_v^0.99.4/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webtorrent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webtorrent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webtorrent/lib/file-stream' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/file' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/peer' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/rarity-map' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/server' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/tcp-pool' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/torrent' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/webconn' {
  declare module.exports: any;
}

declare module 'webtorrent/webtorrent.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webtorrent/index' {
  declare module.exports: $Exports<'webtorrent'>;
}
declare module 'webtorrent/index.js' {
  declare module.exports: $Exports<'webtorrent'>;
}
declare module 'webtorrent/lib/file-stream.js' {
  declare module.exports: $Exports<'webtorrent/lib/file-stream'>;
}
declare module 'webtorrent/lib/file.js' {
  declare module.exports: $Exports<'webtorrent/lib/file'>;
}
declare module 'webtorrent/lib/peer.js' {
  declare module.exports: $Exports<'webtorrent/lib/peer'>;
}
declare module 'webtorrent/lib/rarity-map.js' {
  declare module.exports: $Exports<'webtorrent/lib/rarity-map'>;
}
declare module 'webtorrent/lib/server.js' {
  declare module.exports: $Exports<'webtorrent/lib/server'>;
}
declare module 'webtorrent/lib/tcp-pool.js' {
  declare module.exports: $Exports<'webtorrent/lib/tcp-pool'>;
}
declare module 'webtorrent/lib/torrent.js' {
  declare module.exports: $Exports<'webtorrent/lib/torrent'>;
}
declare module 'webtorrent/lib/webconn.js' {
  declare module.exports: $Exports<'webtorrent/lib/webconn'>;
}
declare module 'webtorrent/webtorrent.min.js' {
  declare module.exports: $Exports<'webtorrent/webtorrent.min'>;
}
